image: node:10.16
clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git heroku-node
